"""init schema -- all tables from core/db/models.py

Hand-written, not autogenerated (no live DB available yet to generate
against) -- kept in exact sync with models.py; if they ever drift,
models.py is the source of truth, fix this file to match it, not the
other way round.

Revision ID: 0001
Revises:
Create Date: 2026-10-01
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

UUID = postgresql.UUID(as_uuid=True)
TS = sa.DateTime(timezone=True)


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("email", sa.String, nullable=False, unique=True),
        sa.Column("firebase_uid", sa.String, nullable=False, unique=True),
        sa.Column("created_at", TS, nullable=False, server_default=sa.text("now()")),
        sa.Column("last_login_at", TS),
    )

    op.create_table(
        "wallets",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("name", sa.String, nullable=False, unique=True),
        sa.Column("kind", sa.String, nullable=False),
        sa.Column("starting_capital", sa.Float, nullable=False),
        sa.Column("current_cash", sa.Float, nullable=False),
        sa.Column("tds_credit", sa.Float, nullable=False),
        sa.Column("created_at", TS, nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "strategies",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("type", sa.String, nullable=False),
        sa.Column("params", sa.JSON, nullable=False),
        sa.Column("status", sa.String, nullable=False),
        sa.Column("stats", sa.JSON, nullable=False),
        sa.Column("created_at", TS, nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", TS, nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "agents",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("wallet_id", UUID, sa.ForeignKey("wallets.id"), nullable=False, unique=True),
        sa.Column("status", sa.String, nullable=False),
        sa.Column("mode", sa.String, nullable=False),
        sa.Column("created_at", TS, nullable=False, server_default=sa.text("now()")),
        sa.Column("died_at", TS),
    )

    op.create_table(
        "backtests",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("strategy_id", UUID, sa.ForeignKey("strategies.id"), nullable=False),
        sa.Column("params_snapshot", sa.JSON, nullable=False),
        sa.Column("start_date", TS, nullable=False),
        sa.Column("end_date", TS, nullable=False),
        sa.Column("trade_count", sa.Integer, nullable=False),
        sa.Column("net_pnl", sa.Float, nullable=False),
        sa.Column("win_rate", sa.Float, nullable=False),
        sa.Column("profit_factor", sa.Float, nullable=False),
        sa.Column("max_drawdown_pct", sa.Float, nullable=False),
        sa.Column("created_at", TS, nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "decisions",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("wallet_id", UUID, sa.ForeignKey("wallets.id"), nullable=False),
        sa.Column("strategy_id", UUID, sa.ForeignKey("strategies.id")),
        sa.Column("proposal", sa.JSON, nullable=False),
        sa.Column("risk_verdict", sa.String, nullable=False),
        sa.Column("risk_reason", sa.Text, nullable=False),
        sa.Column("executed_trade_id", UUID),
        sa.Column("created_at", TS, nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "positions",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("wallet_id", UUID, sa.ForeignKey("wallets.id"), nullable=False),
        sa.Column("pair", sa.String, nullable=False),
        sa.Column("side", sa.String, nullable=False),
        sa.Column("qty", sa.Float, nullable=False),
        sa.Column("entry_price", sa.Float, nullable=False),
        sa.Column("stop_loss", sa.Float, nullable=False),
        sa.Column("take_profit", sa.Float, nullable=False),
        sa.Column("strategy_id", UUID, sa.ForeignKey("strategies.id")),
        sa.Column("decision_id", UUID, sa.ForeignKey("decisions.id")),
        sa.Column("opened_at", TS, nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("wallet_id", "pair", name="positions_wallet_pair_key"),
    )

    op.create_table(
        "trades",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("wallet_id", UUID, sa.ForeignKey("wallets.id"), nullable=False),
        sa.Column("position_id", UUID, sa.ForeignKey("positions.id")),
        sa.Column("pair", sa.String, nullable=False),
        sa.Column("side", sa.String, nullable=False),
        sa.Column("qty", sa.Float, nullable=False),
        sa.Column("price", sa.Float, nullable=False),
        sa.Column("fee", sa.Float, nullable=False),
        sa.Column("tds", sa.Float, nullable=False),
        sa.Column("slippage", sa.Float, nullable=False),
        sa.Column("pnl", sa.Float),
        sa.Column("strategy_id", UUID, sa.ForeignKey("strategies.id")),
        sa.Column("decision_id", UUID, sa.ForeignKey("decisions.id")),
        sa.Column("executed_at", TS, nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "agent_memory",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("wallet_id", UUID, sa.ForeignKey("wallets.id"), nullable=False),
        sa.Column("strategy_id", UUID, sa.ForeignKey("strategies.id")),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("created_at", TS, nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "equity_history",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("wallet_id", UUID, sa.ForeignKey("wallets.id"), nullable=False),
        sa.Column("series", sa.String, nullable=False),
        sa.Column("equity_inr", sa.Float, nullable=False),
        sa.Column("cash_inr", sa.Float, nullable=False),
        sa.Column("holdings_value_inr", sa.Float, nullable=False),
        sa.Column("tds_credit_inr", sa.Float, nullable=False),
        sa.Column("recorded_at", TS, nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("wallet_id", "series", "recorded_at", name="equity_history_series_point_key"),
    )

    op.create_table(
        "llm_calls",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("wallet_id", UUID, sa.ForeignKey("wallets.id")),
        sa.Column("node", sa.String, nullable=False),
        sa.Column("provider", sa.String, nullable=False),
        sa.Column("model", sa.String, nullable=False),
        sa.Column("input_tokens", sa.Integer),
        sa.Column("output_tokens", sa.Integer),
        sa.Column("latency_ms", sa.Integer, nullable=False),
        sa.Column("success", sa.Boolean, nullable=False),
        sa.Column("error", sa.Text),
        sa.Column("created_at", TS, nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "control_commands",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("wallet_id", UUID, sa.ForeignKey("wallets.id")),
        sa.Column("command", sa.String, nullable=False),
        sa.Column("payload", sa.JSON, nullable=False),
        sa.Column("status", sa.String, nullable=False),
        sa.Column("created_at", TS, nullable=False, server_default=sa.text("now()")),
        sa.Column("applied_at", TS),
    )

    op.create_table(
        "settings",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("key", sa.String, nullable=False, unique=True),
        sa.Column("value", sa.JSON, nullable=False),
        sa.Column("updated_at", TS, nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "market_cache",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("pair", sa.String, nullable=False, unique=True),
        sa.Column("min_quantity", sa.Float, nullable=False),
        sa.Column("max_quantity", sa.Float, nullable=False),
        sa.Column("step", sa.Float, nullable=False),
        sa.Column("min_notional", sa.Float, nullable=False),
        sa.Column("base_precision", sa.Integer, nullable=False),
        sa.Column("target_precision", sa.Integer, nullable=False),
        sa.Column("order_types", sa.JSON, nullable=False),
        sa.Column("raw", sa.JSON, nullable=False),
        sa.Column("refreshed_at", TS, nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "locks",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("name", sa.String, nullable=False, unique=True),
        sa.Column("locked_until", TS),
        sa.Column("holder", sa.String, nullable=False),
    )

    op.create_table(
        "heartbeats",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("source", sa.String, nullable=False, unique=True),
        sa.Column("last_beat_at", TS, nullable=False, server_default=sa.text("now()")),
        sa.Column("detail", sa.JSON, nullable=False),
    )

    op.create_table(
        "logs",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("level", sa.String, nullable=False),
        sa.Column("source", sa.String, nullable=False),
        sa.Column("message", sa.Text, nullable=False),
        sa.Column("detail", sa.JSON),
        sa.Column("created_at", TS, nullable=False, server_default=sa.text("now()")),
    )

    op.create_table(
        "alerts_sent",
        sa.Column("id", UUID, primary_key=True),
        sa.Column("wallet_id", UUID, sa.ForeignKey("wallets.id")),
        sa.Column("alert_type", sa.String, nullable=False),
        sa.Column("payload", sa.JSON, nullable=False),
        sa.Column("sent_at", TS, nullable=False, server_default=sa.text("now()")),
    )


def downgrade() -> None:
    for table in [
        "alerts_sent", "logs", "heartbeats", "locks", "market_cache", "settings",
        "control_commands", "llm_calls", "equity_history", "agent_memory", "trades",
        "positions", "decisions", "backtests", "agents", "strategies", "wallets", "users",
    ]:
        op.drop_table(table)
